# Generated by Django 4.2.7 on 2023-12-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_purchased',
            field=models.DateField(auto_now_add=True),
        ),
    ]
