# Generated by Django 4.2.7 on 2023-12-05 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_date_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_purchased',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
