# Generated by Django 4.2.7 on 2023-11-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_groupcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='m_category',
        ),
        migrations.AddField(
            model_name='category',
            name='g_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.groupcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='m_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.maincategory'),
            preserve_default=False,
        ),
    ]
