# Generated by Django 4.2.7 on 2023-11-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_m_category_category_g_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='g_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.groupcategory'),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='m_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_categories', to='products.maincategory'),
        ),
    ]
