# Generated by Django 4.2.7 on 2023-11-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_g_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablesize',
            name='mini_order_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliablesize',
            name='opening_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
