# Generated by Django 4.2.7 on 2023-11-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_avaliablesize_mini_order_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablesize',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
