# Generated by Django 4.2.7 on 2023-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image_alter_productimage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablesize',
            name='orginal_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
