# Generated by Django 4.2.7 on 2023-11-30 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='wishlisted_by',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
