# Generated by Django 4.2.7 on 2023-12-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_store_wishlisted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='brand',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='img/hero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='topic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='vendor',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
