# Generated by Django 4.2.7 on 2023-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_subcategory_brand_subcategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='vendor',
        ),
        migrations.AddField(
            model_name='category',
            name='image_hero',
            field=models.ImageField(default=1, upload_to='img/hero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_hero',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='topic_hero',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='vendor_hero',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
