# Generated by Django 4.2.7 on 2023-12-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_subcategory_brand_remove_subcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_hero',
            field=models.ImageField(blank=True, null=True, upload_to='img/hero'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_hero',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='topic_hero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='vendor_hero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
