# Generated by Django 4.2.7 on 2023-12-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_image_hero_alter_category_title_hero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hero', models.CharField(blank=True, max_length=150, null=True)),
                ('image_hero', models.ImageField(blank=True, null=True, upload_to='img/hero')),
                ('topic_hero', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_hero', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
        ),
    ]
