# Generated by Django 4.2.7 on 2023-12-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_hero_subcategory_h_hero_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='category',
        ),
        migrations.AddField(
            model_name='hero',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.store'),
            preserve_default=False,
        ),
    ]
