# Generated by Django 4.2.7 on 2023-12-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_hero_category_hero_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_hero',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_hero',
        ),
        migrations.RemoveField(
            model_name='category',
            name='topic_hero',
        ),
        migrations.RemoveField(
            model_name='category',
            name='vendor_hero',
        ),
    ]
