# Generated by Django 4.2.7 on 2023-12-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_avaliablesize_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
