# Generated by Django 4.2.7 on 2023-12-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='stock',
            field=models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], default='IN STOCK', max_length=200),
        ),
    ]
